apiVersion: v1
kind: Service
metadata:
  labels:
    app: getting-started
    service: getting-started
  name: getting-started
  namespace: s3c-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: getting-started
  type: ClusterIP
