apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-deployment
  name: hello-world-app
  namespace: hello-world
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - image: opeomotayo/hello-world:latest
        name: hello-world-app

# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: hello-world-deployment
#   namespace: hello-world
#   labels:
#     app: hello-world-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hello-world-app
#   template:
#     metadata:
#       labels:
#         app: hello-world-app
#     spec:
#       containers:
#       - name: hello-world-app
#         image: "opeomotayo/hello-world:latest"
#         # ports:
#         #   - containerPort: 3000
