apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-app
  name: hello-world-deployment
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: opeomotayo/hello-world:latest
        ports:
          - containerPort: 3000
