---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
  labels:
    app: hello-world-service
spec:
  ports:
  - port: 80
    targetPort: 3333
  selector:
    app: hello-world-app