apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: staging
spec:
  encryptedData:
    token: AgCWabfrxZkG8BV8ZRhPXBdlCzTRqNIQZeQAyMN4SnGlFPqO0dsuj8ZpflbuDrhAeaNxWLhwXQjyuwyxYsUf65rdpxYTwMP1GudkZvrsWuVvtYvux8quGUBHS9XklEB6ocqZkP0uyrYS0hOhw2cHYnNGav4BKnaXoupixBsFCRwlte0wpLppytz2mrzB3LPHBmpCbUO61S4Yu+7JLvZQMbHrvW58LIfOqMk2Qs1j9usRx4NXSapfKP6Rs1sMdEyN+YWkhy7P8ICfWiKGtDy4kMNg5kcL0hiHMCjZOfUNPvj8jabyI6+UypUXzxPkH+afOESwDJ3K9LttWRatGO5kFWGIwPUaRy6kaS87MkJeXjwAeytSmFSoEK+HV9My8H1aaWfSslHNPSgOlQ8mAAj124ld9yjvyIlt2LelA+sl319u/am62tVHStIdVc05hrGw/yoOWfs0cOvLKMYImjCnKWbP7b2PYRLWqXr8u4V+CUvirZmyhuRQY5BeG62YF70kd2CrzjOLbWTgUFv5WC+7mALnmHke2D+sk7UQhSjqcoP5UFh/W2t65+ksZAbNFLZo2/m/TwLfJerXjxar1WYsaH2AR/MCDYLm+BeZe/puXw02lbcHB+hRlfs6eHsu7cCpFwxmbFTeJ/1X9X3Q9Roy0/7QVjOWi3lylMnSZzxFpDF8rN1c0YYnIKIrmceofnADXYjFvlPp2rzxPc3/iw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: staging
    type: Opaque

