apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-production
  namespace: flask
spec:
  secretName: flask-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - flask.opeomotayo.net
    
