name: Dockerfile Vulnerability Scan

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkov Dockerfile Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./sample-dockerfile
          framework: dockerfile
