name: Dockerfile Vulnerability Scan

on:
  push: #workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkov Dockerfile Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: ./dockerfile-selfhosted-runner
          framework: dockerfile
