on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      contents: write # tests create releases
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: list files
        run: ls -la

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: software-supply-lifecycle/slsa-provenance-action/go.mod
          check-latest: true
          cache: true

      # - name: Get dependencies
      #   run: make download