name: Container Image SLSA

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shared-services

jobs:
  image_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # outputs:
    #   image-url: ${{ steps.container_info.outputs.image-url }}
    #   image-name: ${{ steps.container_info.outputs.image-name }}
    #   image-digest: ${{ steps.container_info.outputs.image-digest }}
    #   image-tags: ${{ steps.container_info.outputs.image-tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./container-image-security/app-image
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}