name: Docker CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: signedcontainer

jobs:
  image_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image-url: ${{ steps.container_info.outputs.image-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./slsa
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
      
      - name: Get container info
        id: container_info
        run: |
          image_url="${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}"
          echo "::set-output name=image-url::${image_url}"
    
  image_sign:
    runs-on: ubuntu-latest
    needs: [image_build]
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_URL: ${{ needs.image_build.outputs.image-url }}
      
    steps:
      - name: Log into registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
        
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${IMAGE_URL}

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.pubkey'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      
      - name: Verify the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: | 
          echo "::notice title=Verify signature cosign verify --key cosign.pubkey ${IMAGE_URL} | jq '.[0]'"
          echo "::notice title=Inspect signature bundle cosign verify --key cosign.pubkey ${IMAGE_URL} | jq '.[0].optional.Bundle.Payload.body |= @base64d | .[0].optional.Bundle.Payload.body | fromjson'"
          echo "::notice title=Inspect certificate cosign verify --key cosign.pubkey ${IMAGE_URL} | jq -r '.[0].optional.Bundle.Payload.body |= @base64d | .[0].optional.Bundle.Payload.body | fromjson | .spec.signature.publicKey.content |= @base64d | .spec.signature.publicKey.content' | openssl x509 -text"

  image_sbom:
    runs-on: ubuntu-latest
    needs: [image_build]

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_URL: ${{ needs.image_build.outputs.image-url }}

    steps:
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.7.0

      - name: Login to ghcr.io
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Attach SBOM to image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          syft "${IMAGE_URL}" -o spdx-json=sbom-spdx.json
          cosign attest --key cosign.key --predicate sbom-spdx.json --type spdx "${IMAGE_URL}"
          echo "::notice title=Verify SBOM attestation cosign verify-attestation --key cosign.key ${IMAGE_URL}"
          echo "::notice title=Download SBOM attestation cosign download attestation --key cosign.key ${IMAGE_URL} | jq '.payload |= @base64d | .payload | fromjson | select(.predicateType == \"https://spdx.dev/Document\") | .predicate.Data | fromjson'"

      - name: Get SBOM
        id: vars
        run: echo ::set-output name=sbomfile::$(cat sbom-spdx.json)
      - name: Test output
        run: echo ${{ steps.vars.outputs.sbomfile }}