name: Docker CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: signedcontainer

jobs:
  imagebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image-url: ${{ steps.container_info.outputs.image-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ./slsa
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
      
      - name: Get container info
        id: container_info
        run: |
          image_url="${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}"
          echo "::set-output name=image-url::${image_url}"
    
  imagesign:
    runs-on: ubuntu-latest
    needs: [imagebuild]

    env:
      IMAGE_URL: ${{ needs.imagebuild.outputs.image-url }}
      
      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
        
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${IMAGE_URL}

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.pubkey'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      
      - name: Verify the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: | 
          echo "::notice title=Verify signature cosign verify --key cosign.pubkey ${IMAGE_URL} | jq '.[0]'"
          echo "::notice title=Inspect signature bundle cosign verify --key cosign.pubkey ${IMAGE_URL} | jq '.[0].optional.Bundle.Payload.body |= @base64d | .[0].optional.Bundle.Payload.body | fromjson'"
          echo "::notice title=Inspect certificate cosign verify --key cosign.pubkey ${IMAGE_URL} | jq -r '.[0].optional.Bundle.Payload.body |= @base64d | .[0].optional.Bundle.Payload.body | fromjson | .spec.signature.publicKey.content |= @base64d | .spec.signature.publicKey.content' | openssl x509 -text"
