name: Release

on:
  push:
    tags:
      - v**

env:
  IMAGE_NAME: ghcr.io/marcofranssen/slsa-workflow-examples-docker

jobs:
  docker:
    runs-on: ubuntu-20.04

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Login to ghcr.io
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: |
          revision="$(git rev-parse "${GITHUB_REF_NAME:-HEAD}")"
          docker build \
            -t "${IMAGE_NAME}:latest" \
            -t "${IMAGE_NAME}:${GITHUB_REF_NAME}" \
            -t "${IMAGE_NAME}:${revision}" \
            --label "org.opencontainers.image.source=https://github.com/marcofranssen/slsa-workflow-examples" \
            --label "org.opencontainers.image.created=$(date --iso-8601=seconds)" \
            --label "org.opencontainers.image.title=slsa-workflow-examples-docker" \
            --label "org.opencontainers.image.revision=${revision}" \
            --label "org.opencontainers.image.version=${GITHUB_REF_NAME}" \
            --label "org.opencontainers.image.licenses=MIT" \
            --label "org.opencontainers.image.vendor=Marco Franssen" \
            .

      - name: Publish Docker images
        run: docker push "${IMAGE_NAME}" --all-tags
